---
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta2
metadata:
  name: http
  namespace: df-java
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: df1
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Pods
    pods:
      metric:
        name: app_threads
      target:
        type: AverageValue
        averageValue: 300
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80